Jenkinsfile: don't delete pods during teardown
The pods will be automatically deleted by OpenShift when we delete the
associated deployment. If we try to explicitly delete the pods
ourselves, it will occasionally fail due to a race condition (we try to
delete the pod but it's already gone):

    ERROR: Error during delete;
    {reference={}, err=Error from server (NotFound): pods "waiverdb-test-jenkins-waiverdb-49-web-1-jqs0a" not found, verb=delete, cmd=oc delete dc,deploy,pod,configmap,secret,svc,route -l environment=test-jenkins-waiverdb-49 --server=https://open.paas.redhat.com/ --namespace=waiverdb-test --token=XXXXX , out=deploymentconfig "waiverdb-test-jenkins-waiverdb-49-database" deleted
    deploymentconfig "waiverdb-test-jenkins-waiverdb-49-web" deleted
    pod "waiverdb-test-jenkins-waiverdb-49-database-1-x6dka" deleted
    pod "waiverdb-test-jenkins-waiverdb-49-web-1-raf5x" deleted
    configmap "waiverdb-test-jenkins-waiverdb-49-configmap" deleted
    secret "waiverdb-test-jenkins-waiverdb-49-secret" deleted
    service "waiverdb-test-jenkins-waiverdb-49-database" deleted
    service "waiverdb-test-jenkins-waiverdb-49-web" deleted
    route "waiverdb-test-jenkins-waiverdb-49-web" deleted, status=1}