Jenkinsfile: fix FROM fingerprinting in docker build
It was failing like this:

    java.io.IOException: java.io.FileNotFoundException: /home/jenkins/workspace/waiverdb/waiverdb_rpm=mock-result/el7/waiverdb-0.1-0.git.36.f5bc26b.el7.centos.noarch.rpm/Dockerfile (No such file or directory)

because the Docker Pipeline plugin does some dodgy word splitting and
parsing of the docker build arguments, and assumes that the source
directory is always given last on the command line.